### ISSUE TITLE
Interface with C++ STL containers

### ISSUE THREAD

**Issue by SSoulaimane** [dlang/project-ideas#55]
Advance the ongoing effort to make C++ STL containers usable from D.
The project seed is here https://github.com/dlang-cpp-interop/stl-containers.

## What are rough milestones of this project?
- [ ] Provide a solution to hooking move semantics in D.
- [ ] Fix DMD ABI and mangling issues which affect C++ interoperability
- [ ] Finish the implementation of STL containers

**Comment by RazvanN7** [comment]
@SSoulaimane I think it would be really helpful to post the progress you've made on this page, so that whoever picks up work has a good starting point.

**Comment by mdparker** [comment]
There was a successful SAOC 2023 project to [enhance STL container support in the stdcpp repo](https://github.com/Emmankoko/stdcpp/tree/Set2_W). Move semantics is on Walter's radar in the form of DIP 1048 and other work. I don't know what the state of the mangling issues is, or even which issues the description refers to. At any rate, the project as described is no longer valid. If more STL support is needed, someone should open a new issue with the details.
