### ISSUE TITLE
iOS support in LDC

### ISSUE THREAD

**Issue by burner** [dlang/project-ideas#8]
Mobile is becoming, or rather is already, the biggest software platform.
While LDC already supports the Android platform there\'s no official
support for iOS. The project would consist of adding support for the iOS
platform to the LDC compiler, the D runtime library and the D standard
library. The goal would be to get support for this platform upstreamed
to the LDC main project.

A lot of existing work has been done but has never been completed or
upstreamed: (https://github.com/smolt/ldc-iphone-dev)

Proposed Project Mentors: TBA (LDC dev team)

Point of Contact: @jacob-carlborg

**Comment by zoujiaqing** [comment]
wanted ..

**Comment by burner** [comment]
please use the +1 functionality of github to keep these issues neat and tidy. Thank you

**Comment by adamdruppe** [comment]
extern(Objective-C) should be implemented in ldc, that's the #1 priority in adding such support.

**Comment by jacob-carlborg** [comment]
This is completed.

**Comment by RazvanN7** [comment]
@jacob-carlborg Can we close this project or is there anything else to do?

**Comment by jacob-carlborg** [comment]
@RazvanN7 the CI pipeline is broken and I think something in Phobos and/or druntime has regressed. But I think that would fall under a regular issue. It's not up to me if this should be closed or not.
