### ISSUE TITLE
Separate `core.stdcpp` into its own library

### ISSUE THREAD

**Issue by Geod24** [dlang/project-ideas#93]
## Description

Currently, `druntime` contains `core.stdcpp`. This creates a few problems, and was essentially a mistake.
It needs to be moved to its own repository. This has been approved by Walter.

## What are rough milestones of this project?

- Create a repository for `core.stdcpp`;
- Copy the code the code there;
- Put in place a comprehensive CI, which uses DMD at least, ideally LDC and GDC as well;
- Add a `dub` package;
- Deprecate the bindings in druntime;

## How does this project help the D community?

Improving C++ integration.

## References

This has been discussed in the Industry meeting. I (@Geod24 ) brought it up and @WalterBright approved it.

**Comment by 12345swordy** [comment]
How does this project improve c++ integration?

**Comment by Geod24** [comment]
Currently `core.stdcpp` needs to be compiled in druntime, which limits usage to a single C++ std lib, the one we decide to compile with.

**Comment by Geod24** [comment]
This is in progress under https://github.com/dlang/stdcpp

**Comment by mdparker** [comment]
@Geod24 Can this be removed from the projects list? Or should it be modified/resubmitted to reflect the current state of the repo?

**Comment by mdparker** [comment]
On second thought, I'll go ahead and close it. If there's more work to be done on it, please open a new issue as a new project describing what needs to be done.
